// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTbyUzry2HNh71ExlIqycfg_MjiC2i9Rw',
    appId: '1:463417894806:web:f4aa6c23d3b30f614f9fb7',
    messagingSenderId: '463417894806',
    projectId: 'wasel-app-1a87a',
    authDomain: 'wasel-app-1a87a.firebaseapp.com',
    storageBucket: 'wasel-app-1a87a.appspot.com',
    measurementId: 'G-V4B352MM7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwXi7pQe_gSOa0diJnUlrlNICuHdsqcM',
    appId: '1:463417894806:android:6271b6a2994bd2854f9fb7',
    messagingSenderId: '463417894806',
    projectId: 'wasel-app-1a87a',
    storageBucket: 'wasel-app-1a87a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxI-8Qg8Vs_NRye3LZiDaICONXGc8MT8',
    appId: '1:463417894806:ios:b4f17f501180903a4f9fb7',
    messagingSenderId: '463417894806',
    projectId: 'wasel-app-1a87a',
    storageBucket: 'wasel-app-1a87a.appspot.com',
    iosBundleId: 'com.example.waselApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnxI-8Qg8Vs_NRye3LZiDaICONXGc8MT8',
    appId: '1:463417894806:ios:b4f17f501180903a4f9fb7',
    messagingSenderId: '463417894806',
    projectId: 'wasel-app-1a87a',
    storageBucket: 'wasel-app-1a87a.appspot.com',
    iosBundleId: 'com.example.waselApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTbyUzry2HNh71ExlIqycfg_MjiC2i9Rw',
    appId: '1:463417894806:web:506e57efa5417f024f9fb7',
    messagingSenderId: '463417894806',
    projectId: 'wasel-app-1a87a',
    authDomain: 'wasel-app-1a87a.firebaseapp.com',
    storageBucket: 'wasel-app-1a87a.appspot.com',
    measurementId: 'G-H5ZS1PQQCJ',
  );

}